### PR TITLE
Fix missing expiry link check

### LINKED ISSUE #13: Download link expiry not enforced
The expiry date of a download link does not seem to be enforced.
I had a quick look at the code and you verify the integrity of the expiry date in the query string, but you never check whether the expiry date has already passed before requesting the file at the storage backend, do you?

### PR DESCRIPTION
**Pull request by MariusDieckmann**
Fixes #13. Link expiry dates are now explicitly checked.

### CODE REVIEW

File: src/presign_handler/signer.rs [hunk 1]
```diff
@@ -110,9 +110,23 @@ impl PresignHandler {
         mac.update(query_signature.as_bytes());
 
         match mac.verify_slice(signature_hmac_key.as_slice()) {
-            Ok(_) => Ok(true),
-            Err(_) => Ok(false),
+            Ok(_) => {}
+            Err(_) => return Ok(false),
         }
+
```
Comment (St4NNi) [inline src/presign_handler/signer.rs:116]: Should work for now but might be a good idea to give this invalid information to the user.

**Review by St4NNi — APPROVED** [review]
